name: build
on: push
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: jlumbroso/free-disk-space@v1.3.1
        with:
          tool-cache: true
      - uses: actions/checkout@v5
      - uses: bazel-contrib/setup-bazel@0.15.0
        with:
          bazelrc: common --compilation_mode=opt
          disk-cache: true
          external-cache: true
          repository-cache: true
      - run: bazel build //...
