name: build
on: push
jobs:
  build:
    runs-on: blacksmith-8vcpu-ubuntu-2204
    steps:
      - uses: actions/checkout@v5
      - uses: bazel-contrib/setup-bazel@0.15.0
        with:
          bazelrc: common --compilation_mode=opt
          disk-cache: true
          external-cache: true
          repository-cache: true
      - run: bazel build //...
