name: build
on: push
jobs:
  build:
    runs-on: blacksmith-8vcpu-ubuntu-2204
    steps:
      - uses: actions/checkout@v5
      - name: Install dotenvx
        run: curl -L -o dotenvx.tar.gz "https://github.com/dotenvx/dotenvx/releases/latest/download/dotenvx-$(uname -s)-$(uname -m).tar.gz" && tar -xzf dotenvx.tar.gz
      - uses: bazel-contrib/setup-bazel@0.15.0
        with:
          disk-cache: true
          external-cache: true
          repository-cache: true
      - name: Build
        run: ./dotenvx run -- bash -c 'bazel build --config=ci --remote_header=x-buildbuddy-api-key=$BUILDBUDDY_API_KEY //...'
        env:
          DOTENV_PRIVATE_KEY_CI: ${{ secrets.DOTENV_PRIVATE_KEY_CI }}
