name: terraform
on: { push: { branches: [main] } }
jobs:
  apply:
    runs-on: blacksmith-2vcpu-ubuntu-2404-arm
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v5
      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/22128417358/locations/global/workloadIdentityPools/github/providers/marrow
      - uses: hashicorp/setup-terraform@v3
      - name: Terraform Init
        run: terraform init -input=false
      - name: Terraform Apply
        run: terraform apply -auto-approve
